config/routes.rb
MiningApp::Application.routes.draw do

  match '/workers/update', to: 'workers#update', via: :put
  resources :users do
     resources :workers, only: [:new, :create, :destroy, :show, :edit]
  end 
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'info_pages#home'
  get '/contact', to: 'info_pages#contact'
  get '/about', to: 'info_pages#about'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete 
  get '/pools', to: 'pools#new'
  get '/settings', to: 'info_pages#settings'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  coins           :string(255)
#

class User < ActiveRecord::Base
  has_many :workers, dependent: :destroy
  has_secure_password                                              
  
  before_save { email.downcase! }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 7 }, format: { with: VALID_NAME_REGEX }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  #validates :coins, presence: true, format: { with: VALID_COINS_REGEX }
  def User.new_remember_token
      SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
        self.remember_token = User.encrypt(User.new_remember_token)
    end


end             

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

    def show
        @user = User.find(params[:id])
        if @user != current_user
            redirect_to(current_user)
        end
        @workerArray = @user.workers
        @workerArray.each do |work|
            if((DateTime.now.to_time - work.updated_at.to_time) < (6.25 * 60) and work.online) #6.25 minutes
            else
                work.online = false
                work.save
            end
        end
    end 

    def new
        @user = User.new
    end

    def create
        @user= User.new(user_params)
        @user.name.strip!
        if(verify_recaptcha(model: @user, private_key: ENV['RECAPTCHA_PRIVATE_KEY'], timeout: 10) && @user.save)
              sign_in(@user)
              flash[:success] = "Welcome to Miners Canary"
              redirect_to @user
        else
              flash.delete(:recaptcha_error)
              @user.errors.add(:base, I18n.t(:wrong_captcha))
              render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end
       

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(params[:user])
            flash[:success] = "Information updated"
            redirect_to(@user)
        else
            render 'edit'
        end
    end

    private
    def signed_in_user
        unless signed_in?
            store_location
            redirect_to signin_url, notice: "Please Sign in."
        end
    end

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
        @user = User.find(params[:id])
        redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit.html.erb
<div class="page-header">
    <h1>Update your information</h1>
</div>
<div class = "row">
    <div class="span6 offset3">
        <%= form_for(@user) do |u| %>
            <%= render 'shared/user_error_msg' %>

            <%= u.label :name %>
            <%= u.text_field :name %>


            <%= u.label :email %>
            <%= u.text_field :email %>

            <%= u.label :coins, "Coins in wallet" %>
            <%= u.text_field :coins %>

            <%= u.label :password %>
            <%= u.password_field :password %>


            <%= u.label :password_confirmation, "Confirm Password" %>
            <%= u.password_field :password_confirmation %>

            <%= u.submit "Save changes", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@user) do |u| %>
            <%= render 'shared/user_error_msg' %>

            <%= u.label :name %>
            <%= u.text_field :name %>

            <%= u.label :email %>
            <%= u.text_field :email %>

            <%= u.label :password %>
            <%= u.password_field :password %>

            <%= u.label :password_confirmation, "Confirmation" %>
            <%= u.password_field :password_confirmation %>

            <%= recaptcha_tags display: { ssl: true, theme: 'clean' , tabindex: 1, public_key: ENV['RECAPTCHA_PUBLIC_KEY'] }%> 
            
            <%= u.submit "Create my account", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="page-header">
    <h1>Workers Statistics <small><%=@user.name %>'s miners</small></h1>
</div>    
<% @workerCount = @user.workers.size %>
<% if @workerCount == 0 %>
    <p> You have zero workers add workers from drop down menu Account</p>
<%else%>
	<% @workerArray = @user.workers%>
	<table data-provides="rowlink" class="table table-bordered">
	 <thead>
	  <tr>
         <th>Worker Name</th>
        <th>Status</th>
		<th>Total Hashrate</th>
		<th>Accepted Shares</th>
		<th>Rejected Shares</th>
		<th>Hardware Errors</th>
		<th>Number of GPUs</th>
	  </tr>
	  </thead>
	  <tbody data-provides="rowlink">
          <% @workerArray.each do |work|%>
          <%if(work.online == false) %>
          <%elsif (work.GPUT1 != nil && work.GPUT1 > 89) || (work.GPUT2 != nil && work.GPUT2 > 89) || (work.GPUT3 != nil && work.GPUT3 > 89) || (work.GPUT4 != nil && work.GPUT4 > 89)%>   
            <tr class="error">
          <%elsif (work.GPUT1 != nil && work.GPUT1 > 81) || (work.GPUT2 != nil && work.GPUT2 > 81) || (work.GPUT3 != nil && work.GPUT3 > 81) || (work.GPUT4 != nil && work.GPUT4 > 81)%>
            <tr class="warning">
          <%else%>
            <tr class="success">
          <%end%>
          <td><a href=<%=user_worker_path(@user,work)%>><%=work.name%></a></td>
          <td><%= work.online ? "Online" : "Offline @ " + work.updated_at.to_s()%></td>
		  <td><%= work.online ? work.hashrate.to_s() + " KH/s" : "0"%></td>
		  <td><%= work.online ? work.accepted : 0%></td>
		  <td><%= work.online ? work.rejected : 0%></td>
		  <td><%= work.online ? work.hw_errors : 0%></td>
		  <td><%=work.num_gpu%></td>
		</tr>
	 <%end%> 
	 </tbody>
 </table>
 <button type="button" class = "btn" data-toggle="collapse" data-target="#legend">Legend</button>
 <div id="legend" class="collapse">
     <ul>
         <li><small>Green row means all GPUs are under 78 degrees Celsius</small></li>
         <li><small>Yellow row means any GPU is above 80 degrees but below 89 degrees Celsius</small></li>
         <li><small>Red row means any GPU is above 89 degrees Celsius</small></li>
         <li><small>White row means the Worker is ofline</small></li>
     </ul>
 </div>
 <%end%>