config/routes.rb
MiningApp::Application.routes.draw do

  match '/workers/update', to: 'workers#update', via: :put
  resources :users do
     resources :workers, only: [:new, :create, :destroy, :show, :edit]
  end 
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'info_pages#home'
  get '/contact', to: 'info_pages#contact'
  get '/about', to: 'info_pages#about'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete 
  get '/pools', to: 'pools#new'
  get '/settings', to: 'info_pages#settings'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
    Website by Elliot Weil
</small>
 <nav>
  <ul>
      <li><%= link_to "About",   about_path  %></li>
      <li><%= link_to "Contact", contact_path  %></li>
  </ul>
 </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
 <div class ="navbar-inner">
     <div class="container">
      <%= link_to "CryptoCanary", root_path ,id:"logo" %> 
      <span class="label label">LTC price:$<%= 0 %> </span>
      <span class="label label-warning">BTC Price:$<%= 0  %> </span>
       <ul class="nav pull-right">
           <li><%= link_to "Home", root_path %></li>
           <% if signed_in?() %>
               <li> <%= link_to "Stats", current_user%></li>
               <li id=fat-menu class="dropdown">
                <a hred= "#" class="dropdown-toggle" data-toggle="dropdown">
                    Account<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                 <li><%= link_to "Add a Worker", new_user_worker_path(current_user)%></li>
                 <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                 <li class="divider"><li>
                 <li>
                 <%= link_to "Sign out", signout_path, method: "delete"%>
                 </li>
                </ul>
               </li>
           <% else %>
               <li><%= link_to "Sign in", signin_path %> </li>
           <%end%>
       </ul>
      </nav>
  </div>
 </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CryptoCanary</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
 <%= render 'layouts/header' %>
 <div class="container">
     <% flash.each do |key, value| %>
         <div class="alert alert-<%=key%>"><%=value%></div>
     <%end%>
     <%= yield %>
     <%= render 'layouts/footer' %>
     <%= debug(params) if Rails.env.development? %>
 </div>
</body>
</html>

app/views/layouts/oldapplication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> EJW Mining Monitoring Web App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>